### ISSUE TITLE
Error while value grouping training.

### ISSUE THREAD

**Issue by AnujCodeZ** [xinyangz/OAMine#3]
While training, iteration is complete and metrics are shown, this error occurs.
Epoch:   0%|                                                                                                                                                            | 0/10 [02:45<?, ?it/s]
Error executing job with overrides: ['run.train_gpu=0', 'run.exp_dir=/home/ubuntu/oa_mine/OAMine/value_grouping/outputs', 'run.iter_num=1', 'run.rnd_seed=123']
Traceback (most recent call last):
  File "/home/ubuntu/oa_mine/OAMine/value_grouping/src/sbert_multitask.py", line 101, in main
    model.fit(train_objectives=train_objectives,
  File "/home/ubuntu/miniconda3/envs/linkmatch/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 745, in fit
    self._eval_during_training(evaluator, output_path, save_best_model, epoch, -1, callback)
  File "/home/ubuntu/miniconda3/envs/linkmatch/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 777, in _eval_during_training
    score = evaluator(self, output_path=eval_path, epoch=epoch, steps=steps)
  File "/home/ubuntu/miniconda3/envs/linkmatch/lib/python3.10/site-packages/sentence_transformers/evaluation/BinaryClassificationEvaluator.py", line 94, in __call__
    file_output_data.append(scores[sim_fct][metric])
KeyError: 'manhattan'

**Comment by xinyangz** [comment]
Looks like an issue with `sentence_transformers` version. Can you make sure it's version 2.0.0?

**Comment by AnujCodeZ** [comment]
> Looks like an issue with `sentence_transformers` version. Can you make sure it's version 2.0.0?

Thanks @xinyangz, error due to version of `sentence_transformers` in spelling of manhattan. Now it's solved.
